name = "SurfaceWaterIntegratedModeling"
uuid = "71e2a337-b4d4-4738-9f2b-3c37e1d3d462"
version = "1.0.3"
authors = ["Odd Andersen <odd.andersen@sintef.no>"]

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ColorSchemes = "3.24"
Colors = "0.12.10, 0.13"

#DifferentialEquations = "7.13"
#GeometryBasics = "0.4.11, 0.5"
#Graphs = "1.9"
#Interpolations = "0.15.1"
#Makie = "0.21, 0.22"
#OffsetArrays = "1.13"
#Roots = "2.1.2"
#julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
